[package]
name = "verdant-drivers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ads1x1x = "0.2.2"
nb = "1.0.0"
embedded-hal = "0.2.7"
linux-embedded-hal = "0.3.2"
